#  ‎ {.unnumbered .unlisted}


While conceptually simple, Bayesian methods can be mathematically and numerically challenging. Probabilistic programming languages (PPLs) implement functions to easily build Bayesian models together with efficient automatic inference methods. This helps separate the model building from the inference, allowing practitioners to focus on their specific problems and leaving the PPLs to handle the computational details for them [@bessiere2013; @daniel2015; @ghahramani2015]. The inference process generates a posterior distribution - which has a central role in Bayesian statistics - together with other distributions like the posterior predictive distribution and the prior predictive distribution. The correct visualization, analysis, and interpretation of these distributions is key to properly answer the questions that motivated the inference process.

When working with Bayesian models there are a series of related tasks that need to be addressed besides inference itself:

* Diagnoses of the quality of the inference (as this is generally done using numerical approximation methods)
* Model criticism, including evaluations of both model assumptions and model predictions
* Comparison of models, including model selection or model averaging
* Preparation of the results for a particular audience

We collectively call all these tasks *Exploratory analysis of Bayesian models*, building on concepts from *Exploratory data analysis* to examine and gain deeper insights into Bayesian models. 

In the words of Persi Diaconis [@diaconis2011]:

> "Exploratory data analysis seeks to reveal structure, or simple descriptions in data. We look at numbers or graphs and try to find patterns. We pursue leads suggested by background information, imagination, patterns perceived, and experience with other data analyses".

In this book we discuss how to use both numerical and visual summaries to successfully perform the many tasks that are central to the iterative and interactive modeling process. To do so, we first discuss some general principles of data visualization and uncertainty representation that are not exclusive of Bayesian statistics.


## Citations

If you are using specific methods or functions from the book, please consider citing the scientific paper and/or corresponding package.

If you want to cite this online book in your research. The following citation is recommended, as it always resolves to the latest version of the book:

> Martin et al. (2025). Exploratory Analysis of Bayesian Models. Zenodo. https://zenodo.org/records/15127549

You can use the following BibTeX entry:

```
@book{eabm_2025,
  author       = {Osvaldo A Martin and Oriol Abril-Pla},
  title        = {Exploratory analysis of Bayesian models},
  month        = apr,
  year         = 2025,
  publisher    = {Zenodo},
  version      = {v0.1.0},
  doi          = {10.5281/zenodo.15127549},
  url          = {https://doi.org/10.5281/zenodo.15127549},
                  },
```

## Donations

If you find this book useful, please consider supporting the authors by making a [donation](https://numfocus.org/donate-to-arviz). This will help us to keep the book updated and to provide more resources in the future.


## License

This book is licensed under the CC-BY-NC 4.0. License. See the [LICENSE](LICENSE) file for details.